export const demoMovies = [
  {
    id: 'demo-1',
    title: 'The Matrix',
    year: '1999',
    poster: 'https://image.tmdb.org/t/p/w500/f89U3ADr1oiB1s9GkdPOEpXUk5H.jpg',
    overview: 'A hacker discovers that reality is not what it seems and joins a rebellion against intelligent machines.',
    tmdbRating: 8.2,
    runtime: 136,
    genres: ['Action', 'Sci-Fi'],
    nominated_by: 'Demo',
  },
  {
    id: 'demo-2',
    title: 'Spirited Away',
    year: '2001',
    poster: 'https://image.tmdb.org/t/p/w500/39wmItIWsg5sZMyRUHLkWBcuVCM.jpg',
    overview: 'A young girl enters a mysterious spirit world and must find courage to rescue her parents.',
    tmdbRating: 8.5,
    runtime: 125,
    genres: ['Animation', 'Fantasy'],
    nominated_by: 'Demo',
  },
  {
    id: 'demo-3',
    title: 'Parasite',
    year: '2019',
    poster: 'https://image.tmdb.org/t/p/w500/7IiTTgloJzvGI1TAYymCfbfl3vT.jpg',
    overview: 'A poor family schemes its way into the life of a wealthy household with unexpected consequences.',
    tmdbRating: 8.5,
    runtime: 133,
    genres: ['Thriller', 'Drama'],
    nominated_by: 'Demo',
  },
]
