export const demoMovies = [
  {
    id: 'movie-matrix',
    title: 'The Matrix',
    year: '1999',
    poster: 'https://image.tmdb.org/t/p/w500/f89U3ADr1oiB1s9GkdPOEpXUk5H.jpg',
    overview: 'A hacker discovers that reality is not what it seems and joins a rebellion against intelligent machines.',
    tmdbRating: 8.2,
    runtime: 136,
    genres: ['Action', 'Sci-Fi'],
    nominated_by: 'Maya',
    picks: 12,
    score: 9,
    rating: 9,
    watched: true,
  },
  {
    id: 'movie-spirited-away',
    title: 'Spirited Away',
    year: '2001',
    poster: 'https://image.tmdb.org/t/p/w500/39wmItIWsg5sZMyRUHLkWBcuVCM.jpg',
    overview: 'A young girl enters a mysterious spirit world and must find courage to rescue her parents.',
    tmdbRating: 8.5,
    runtime: 125,
    genres: ['Animation', 'Fantasy'],
    nominated_by: 'Jonas',
    picks: 10,
    score: 8,
    rating: 10,
    watched: true,
  },
  {
    id: 'movie-parasite',
    title: 'Parasite',
    year: '2019',
    poster: 'https://image.tmdb.org/t/p/w500/7IiTTgloJzvGI1TAYymCfbfl3vT.jpg',
    overview: 'A poor family schemes its way into the life of a wealthy household with unexpected consequences.',
    tmdbRating: 8.5,
    runtime: 133,
    genres: ['Thriller', 'Drama'],
    nominated_by: 'Lena',
    picks: 8,
    score: 7,
    rating: 9,
    watched: false,
  },
  {
    id: 'movie-dune-two',
    title: 'Dune: Part Two',
    year: '2024',
    poster: 'https://image.tmdb.org/t/p/w500/1pdfLvkbY9ohJlCjQH2CZjjYVvJ.jpg',
    overview: 'Paul Atreides unites with Chani and the Fremen while seeking revenge against the conspirators who destroyed his family.',
    tmdbRating: 8.1,
    runtime: 167,
    genres: ['Sci-Fi', 'Adventure'],
    nominated_by: 'Noah',
    picks: 7,
    score: 6,
    rating: null,
    watched: false,
  },
]

export const demoSeries = [
  {
    id: 'series-severance',
    title: 'Severance',
    year: '2022',
    poster: 'https://image.tmdb.org/t/p/w500/lFf6LLrQjYldcZItzOkGmMMigP7.jpg',
    picks: 11,
    score: 9,
  },
  {
    id: 'series-the-bear',
    title: 'The Bear',
    year: '2022',
    poster: 'https://image.tmdb.org/t/p/w500/sHFlbKS3WLqMnp9t2ghADIJFnuQ.jpg',
    picks: 9,
    score: 7,
  },
  {
    id: 'series-arcane',
    title: 'Arcane',
    year: '2021',
    poster: 'https://image.tmdb.org/t/p/w500/fqldf2t8ztc9aiwn3k6mlX3tvRT.jpg',
    picks: 8,
    score: 6,
  },
]

export const demoGames = [
  {
    id: 'game-balatro',
    title: 'Balatro',
    year: '2024',
    poster: 'https://media.rawg.io/media/games/aa1/aa112c207e5f4d8648939c5ff8f20b9d.jpg',
    picks: 13,
    score: 10,
  },
  {
    id: 'game-elden-ring',
    title: 'Elden Ring',
    year: '2022',
    poster: 'https://media.rawg.io/media/games/ba8/ba82c971336adfd290e4c0eab6504fcf.jpg',
    picks: 10,
    score: 8,
  },
  {
    id: 'game-hades',
    title: 'Hades',
    year: '2020',
    poster: 'https://media.rawg.io/media/games/8a3/8a3e912ccefa4243f6297a5b9cdcc2ea.jpg',
    picks: 7,
    score: 6,
  },
]

export const demoVideos = [
  {
    id: 'video-night-drive',
    title: 'Late night playlist',
    year: 'Saved link',
    poster: 'https://img.youtube.com/vi/jfKfPfyJRdk/hqdefault.jpg',
    picks: 6,
    score: 5,
  },
  {
    id: 'video-cooking-chaos',
    title: 'Cooking chaos compilation',
    year: 'Saved link',
    poster: 'https://img.youtube.com/vi/dQw4w9WgXcQ/hqdefault.jpg',
    picks: 5,
    score: 4,
  },
]
