-- Persistent videos for personal libraries and cliques.
-- Videos are saved as external links, so users can add YouTube, TikTok, Instagram, or other video URLs.

create table if not exists public.videos (
  id bigint generated by default as identity primary key,
  group_id uuid references public.groups(id) on delete cascade,
  owner_id uuid references auth.users(id) on delete cascade,
  video_id text not null,
  title text not null,
  url text not null,
  year text,
  poster text,
  backdrop text,
  overview text,
  platform text,
  nominated_by text not null default 'anonymous',
  picks integer not null default 0,
  score integer not null default 0,
  classic boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.videos enable row level security;

create index if not exists videos_group_id_idx on public.videos(group_id);
create index if not exists videos_owner_id_idx on public.videos(owner_id);
create unique index if not exists videos_group_video_unique on public.videos(group_id, video_id);
create unique index if not exists videos_owner_video_unique on public.videos(owner_id, video_id);

drop policy if exists "Videos are readable by owner or group members" on public.videos;
drop policy if exists "Videos are insertable by owner or group members" on public.videos;
drop policy if exists "Videos are updatable by owner or group members" on public.videos;

create policy "Videos are readable by owner or group members" on public.videos
for select to authenticated
using (
  (group_id is null and owner_id = (select auth.uid()))
  or (group_id is not null and private.is_group_member(group_id, (select auth.uid())))
);

create policy "Videos are insertable by owner or group members" on public.videos
for insert to authenticated
with check (
  (group_id is null and owner_id = (select auth.uid()))
  or (group_id is not null and private.is_group_member(group_id, (select auth.uid())))
);

create policy "Videos are updatable by owner or group members" on public.videos
for update to authenticated
using (
  (group_id is null and owner_id = (select auth.uid()))
  or (group_id is not null and private.is_group_member(group_id, (select auth.uid())))
)
with check (
  (group_id is null and owner_id = (select auth.uid()))
  or (group_id is not null and private.is_group_member(group_id, (select auth.uid())))
);

create or replace function public.vote_video(video_id_input text, vote_delta_input integer, group_id_input uuid default null)
returns void
language plpgsql
security definer
set search_path = public, private
as $$
begin
  if auth.uid() is null then
    raise exception 'You must be signed in to vote.';
  end if;

  if group_id_input is not null and not private.is_group_member(group_id_input, auth.uid()) then
    raise exception 'You must be a member of this group to vote.';
  end if;

  update public.videos
  set picks = greatest(0, coalesce(picks, 0) + case when vote_delta_input > 0 then 1 else 0 end),
      score = coalesce(score, 0) + coalesce(vote_delta_input, 0),
      classic = case when vote_delta_input > 0 then true else classic end,
      updated_at = now()
  where video_id = video_id_input
    and (
      (group_id_input is not null and group_id = group_id_input)
      or (group_id_input is null and group_id is null and owner_id = auth.uid())
    );
end;
$$;

grant execute on function public.vote_video(text, integer, uuid) to authenticated;
