-- Persistent games plus public/community leaderboard aggregation.
-- Run this after the auth/groups, movies, and series migrations.

create table if not exists public.games (
  id bigint generated by default as identity primary key,
  group_id uuid references public.groups(id) on delete cascade,
  game_id text not null,
  title text not null,
  year text,
  released date,
  poster text,
  backdrop text,
  overview text,
  rawg_rating numeric,
  genres text[] not null default '{}',
  platform text,
  platforms text[] not null default '{}',
  nominated_by text not null default 'anonymous',
  picks integer not null default 0,
  score integer not null default 0,
  played boolean not null default false,
  my_rating integer,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.games enable row level security;

create index if not exists games_group_id_idx on public.games(group_id);
create unique index if not exists games_group_game_unique on public.games(group_id, game_id);
create unique index if not exists games_global_game_unique on public.games(game_id) where group_id is null;

drop policy if exists "Games are readable by group members" on public.games;
drop policy if exists "Games are insertable by group members" on public.games;
drop policy if exists "Games are updatable by group members" on public.games;

create policy "Games are readable by group members" on public.games
for select to authenticated
using (group_id is null or private.is_group_member(group_id, (select auth.uid())));

create policy "Games are insertable by group members" on public.games
for insert to authenticated
with check (group_id is null or private.is_group_member(group_id, (select auth.uid())));

create policy "Games are updatable by group members" on public.games
for update to authenticated
using (group_id is null or private.is_group_member(group_id, (select auth.uid())))
with check (group_id is null or private.is_group_member(group_id, (select auth.uid())));

create or replace function public.vote_game(game_id_input text, vote_delta_input integer, group_id_input uuid default null)
returns void
language plpgsql
security definer
set search_path = public, private
as $$
begin
  if group_id_input is not null and (auth.uid() is null or not private.is_group_member(group_id_input, auth.uid())) then
    raise exception 'You must be a member of this group to vote.';
  end if;

  update public.games
  set picks = greatest(0, coalesce(picks, 0) + 1),
      score = coalesce(score, 0) + coalesce(vote_delta_input, 0),
      updated_at = now()
  where game_id = game_id_input
    and (group_id_input is null or group_id = group_id_input);
end;
$$;

grant execute on function public.vote_game(text, integer, uuid) to authenticated;

create or replace function public.get_community_leaderboard()
returns jsonb
language sql
stable
security definer
set search_path = public, private
as $$
with media as (
  select
    m.group_id,
    'Movies'::text as category,
    '🎬'::text as icon,
    m.movie_id as item_id,
    m.title,
    m.poster,
    m.nominated_by,
    coalesce(m.score, 0)::integer as score,
    coalesce(m.picks, 0)::integer as picks,
    m.my_rating::numeric as rating,
    coalesce(m.watched, false) as completed
  from public.movies m
  where m.group_id is not null

  union all

  select
    s.group_id,
    'Series'::text as category,
    '📺'::text as icon,
    s.series_id as item_id,
    s.title,
    s.poster,
    s.nominated_by,
    coalesce(s.score, 0)::integer as score,
    coalesce(s.picks, 0)::integer as picks,
    s.my_rating::numeric as rating,
    coalesce(s.finished, false) as completed
  from public.series s
  where s.group_id is not null

  union all

  select
    ga.group_id,
    'Games'::text as category,
    '🎮'::text as icon,
    ga.game_id as item_id,
    ga.title,
    ga.poster,
    ga.nominated_by,
    coalesce(ga.score, 0)::integer as score,
    coalesce(ga.picks, 0)::integer as picks,
    ga.my_rating::numeric as rating,
    coalesce(ga.played, false) as completed
  from public.games ga
  where ga.group_id is not null
),
group_rollup as (
  select
    g.id,
    g.name,
    g.invite_code,
    count(distinct gm.user_id)::integer as member_count,
    count(m.item_id)::integer as item_count,
    coalesce(sum(m.score), 0)::integer as total_score,
    coalesce(sum(m.picks), 0)::integer as total_picks,
    coalesce(sum(case when m.completed then 1 else 0 end), 0)::integer as completed_count,
    round(coalesce(avg(m.rating) filter (where m.rating is not null), 0), 2)::numeric as average_rating
  from public.groups g
  left join public.group_members gm on gm.group_id = g.id
  left join media m on m.group_id = g.id
  group by g.id, g.name, g.invite_code
),
group_top_items as (
  select
    group_id,
    jsonb_agg(
      jsonb_build_object(
        'id', item_id,
        'title', title,
        'category', category,
        'icon', icon,
        'score', score,
        'picks', picks,
        'rating', rating,
        'poster', poster
      )
      order by score desc, picks desc, rating desc nulls last, title asc
    ) filter (where item_rank <= 3) as items
  from (
    select m.*, row_number() over (partition by group_id order by score desc, picks desc, rating desc nulls last, title asc) as item_rank
    from media m
  ) ranked_media
  group by group_id
),
top_content as (
  select
    m.*,
    g.name as group_name,
    g.invite_code,
    row_number() over (order by m.score desc, m.picks desc, m.rating desc nulls last, m.title asc) as content_rank
  from media m
  join public.groups g on g.id = m.group_id
),
ranked_groups as (
  select
    gr.*,
    coalesce(gti.items, '[]'::jsonb) as top_items,
    row_number() over (order by gr.average_rating desc, gr.completed_count desc, gr.total_score desc, gr.total_picks desc, gr.member_count desc, gr.name asc) as group_rank
  from group_rollup gr
  left join group_top_items gti on gti.group_id = gr.id
)
select jsonb_build_object(
  'groups', coalesce((
    select jsonb_agg(
      jsonb_build_object(
        'rank', group_rank,
        'id', id,
        'name', name,
        'inviteCode', invite_code,
        'memberCount', member_count,
        'itemCount', item_count,
        'totalScore', total_score,
        'totalPicks', total_picks,
        'completedCount', completed_count,
        'averageRating', average_rating,
        'topItems', top_items
      )
      order by group_rank
    )
    from ranked_groups
    where group_rank <= 20
  ), '[]'::jsonb),
  'topContent', coalesce((
    select jsonb_agg(
      jsonb_build_object(
        'rank', content_rank,
        'id', item_id,
        'groupId', group_id,
        'groupName', group_name,
        'inviteCode', invite_code,
        'category', category,
        'icon', icon,
        'title', title,
        'poster', poster,
        'nominatedBy', nominated_by,
        'score', score,
        'picks', picks,
        'rating', rating
      )
      order by content_rank
    )
    from top_content
    where content_rank <= 30
  ), '[]'::jsonb),
  'totals', jsonb_build_object(
    'groups', (select count(*) from public.groups),
    'members', (select count(*) from public.group_members),
    'items', (select count(*) from media),
    'picks', coalesce((select sum(picks) from media), 0),
    'score', coalesce((select sum(score) from media), 0)
  )
);
$$;

grant execute on function public.get_community_leaderboard() to anon, authenticated;
