-- Backend storage and policies for group-scoped series piles.
-- Run this after 202605300001_auth_groups_movies.sql.

create table if not exists public.series (
  id bigint generated by default as identity primary key,
  group_id uuid references public.groups(id) on delete cascade,
  series_id text not null,
  title text not null,
  year text,
  released date,
  poster text,
  backdrop text,
  overview text,
  tmdb_rating numeric,
  runtime integer,
  genres text[] not null default '{}',
  seasons integer,
  episodes integer,
  nominated_by text not null default 'anonymous',
  picks integer not null default 0,
  score integer not null default 0,
  finished boolean not null default false,
  my_rating integer,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.series enable row level security;

create index if not exists series_group_id_idx on public.series(group_id);
create unique index if not exists series_group_series_unique on public.series(group_id, series_id);
create unique index if not exists series_global_series_unique on public.series(series_id) where group_id is null;

drop policy if exists "Series are readable by group members" on public.series;
drop policy if exists "Series are insertable by group members" on public.series;
drop policy if exists "Series are updatable by group members" on public.series;

create policy "Series are readable by group members" on public.series
for select to authenticated
using (group_id is null or private.is_group_member(group_id, (select auth.uid())));

create policy "Series are insertable by group members" on public.series
for insert to authenticated
with check (group_id is null or private.is_group_member(group_id, (select auth.uid())));

create policy "Series are updatable by group members" on public.series
for update to authenticated
using (group_id is null or private.is_group_member(group_id, (select auth.uid())))
with check (group_id is null or private.is_group_member(group_id, (select auth.uid())));

create or replace function public.vote_series(series_id_input text, vote_delta_input integer, group_id_input uuid default null)
returns void
language plpgsql
security definer
set search_path = public, private
as $$
begin
  if group_id_input is not null and (auth.uid() is null or not private.is_group_member(group_id_input, auth.uid())) then
    raise exception 'You must be a member of this group to vote.';
  end if;

  update public.series
  set picks = greatest(0, coalesce(picks, 0) + 1),
      score = coalesce(score, 0) + coalesce(vote_delta_input, 0),
      updated_at = now()
  where series_id = series_id_input
    and (group_id_input is null or group_id = group_id_input);
end;
$$;

grant execute on function public.vote_series(text, integer, uuid) to authenticated;
